### ISSUE TITLE
googleapiclient.errors  returned "Request Too Large"

### ISSUE THREAD

**Issue by dipietro-salvatore** [praveendath92/fitbit-googlefit#10]
Hello,
I am tring to import the data to Google Fitness but it start to give me this error, why? 
Thank you very much 

synced steps
synced distance
Traceback (most recent call last):
  File "app.py", line 96, in <module>
    main()
  File "app.py", line 75, in main
    remote.SyncFitbitToGoogleFit('heart_rate',date_stamp)
  File "/home/diego/Downloads/fitbit-googlefit/remote.py", line 125, in SyncFitbitToGoogleFit
    return self.SyncFitbitIntradayToGoogleFit(dataType, date_stamp)
  File "/home/diego/Downloads/fitbit-googlefit/remote.py", line 159, in SyncFitbitIntradayToGoogleFit
    self.WriteToGoogleFit(dataSourceId, googlePoints)
  File "/home/diego/Downloads/fitbit-googlefit/remote.py", line 85, in WriteToGoogleFit
    ).execute()
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 413 when requesting https://www.googleapis.com/fitness/v1/users/me/dataSources/raw%3Acom.google.heart_rate.bpm%3A26454365833%3Afitbit%3Acharge-hr%3Aio.pkp.fbit-gfit/datasets/1467154800000000000-1467241139000000110?alt=json returned "Request Too Large">

**Comment by praveendath92** [comment]
@dipietro-salvatore , Unfortunately these logs doesn't contain enough information to debug. My best guess is an network error. Did you retry and see if the problem persists?

**Comment by praveendath92** [comment]
@dipietro-salvatore , I just noticed the title clearly. This issue is addressed in one of the recent commits. Please try against the latest commit. 

PS: This issue was [resolved 4 days ago](https://github.com/praveendath92/fitbit-googlefit/issues/3#ref-commit-f302c38).

**Comment by praveendath92** [comment]
Feel free to re-open if the problem persists in the latest code.
