### ISSUE TITLE
CherryPy error

### ISSUE THREAD

**Issue by kevincberry** [praveendath92/fitbit-googlefit#12]
I'm encountering a CherryPy error when attempting to authenticate with FitBit's api

`root@sync:/home/fitbit-googlefit-master/auth# python3 auth_fitbit.py 227YZF 7951c07a5b033aedff38ec6002703684
[14/Sep/2016:20:27:07] ENGINE Listening for SIGTERM.
[14/Sep/2016:20:27:07] ENGINE Listening for SIGUSR1.
[14/Sep/2016:20:27:07] ENGINE Listening for SIGHUP.
[14/Sep/2016:20:27:07] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[14/Sep/2016:20:27:07] ENGINE Started monitor thread '_TimeoutMonitor'.
[14/Sep/2016:20:27:07] ENGINE Started monitor thread 'Autoreloader'.
[14/Sep/2016:20:27:12] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7effd5aeba58>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/process/servers.py", line 439, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
OSError: Port 8080 not free on '127.0.0.1'

[14/Sep/2016:20:27:12] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("Port 8080 not free on '127.0.0.1'",)

[14/Sep/2016:20:27:12] ENGINE Bus STOPPING
[14/Sep/2016:20:27:12] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) already shut down
[14/Sep/2016:20:27:12] ENGINE Stopped thread '_TimeoutMonitor'.
[14/Sep/2016:20:27:12] ENGINE Stopped thread 'Autoreloader'.
[14/Sep/2016:20:27:12] ENGINE Bus STOPPED
[14/Sep/2016:20:27:12] ENGINE Bus EXITING
[14/Sep/2016:20:27:12] ENGINE Bus EXITED
`

Is my suspicion that the problem is somewhere outside the fitbit-googlefit app correct? Should I be looking at my server configuration instead of the app to find the problem?

**Comment by praveendath92** [comment]
@kevincberry , Are you trying to run the authentication scripts on a headless server?

**Comment by kevincberry** [comment]
Yes, I'm running it on a Digital Ocean server running Ubuntu.

Should I not be doing that?

**Comment by praveendath92** [comment]
@kevincberry , I run it on a Digital Ocean droplet too - in fact I have setup a cron job to sync daily for a couple of weeks now. 

However, the one-time authentication requires a browser with a display - hence locally and transfer the credentials.

**Comment by kevincberry** [comment]
I'm relatively new to working within a command line environment. Can you
give some more guidance on how to do this in a local environment?

**Comment by praveendath92** [comment]
It works similar to how you set it up on Digital ocean. Just follow the [Setup instructions](https://github.com/praveendath92/fitbit-googlefit#setup) on your local PC. 

If you are using Windows, may be try this inside a Virtual box with Linux VM.

**Comment by kevincberry** [comment]
Great, I've got sorted it out now. 

Thank you!

**Comment by praveendath92** [comment]
Good to know it's working for you 😄
