### ISSUE TITLE
Running app.py fails

### ISSUE THREAD

**Issue by ggrell** [praveendath92/fitbit-googlefit#23]
First time install & run. I was successful with authorizing both FitBit & GFit with fitbit.json and google.json generated). When I run app.py though, I get the following error:

```
------------------------------   2017-01-26  -------------------------
Traceback (most recent call last):
  File "app.py", line 108, in <module>
    main()
  File "app.py", line 74, in main
    remote.SyncFitbitToGoogleFit('steps',date_stamp)
  File "/Users/ggrell/Projects/fitbit-googlefit/remote.py", line 139, in SyncFitbitToGoogleFit
    self.helper.UpdateFitbitCredentials(self.fitbitClient)
  File "/Users/ggrell/Projects/fitbit-googlefit/helpers.py", line 50, in UpdateFitbitCredentials
    credentials[t] = fitbitClient.client.token[t]
AttributeError: 'FitbitOauth2Client' object has no attribute 'token'
```
Mac OS 10.11.6 (El Cap)
Python 3.6.0 installed via HomeBrew

**Comment by praveendath92** [comment]
@ggrell , The latest commit should fix this. Sorry about that. The issue started after a breaking update to one of the dependent libraries.
