### ISSUE TITLE
app.py fails with ValueError: Missing access token.

### ISSUE THREAD

**Issue by jervine** [praveendath92/fitbit-googlefit#27]
Both Google and FitBit json auth files have been created using the utilities. Running app.py fails with the following trace:

Traceback (most recent call last):
  File "app.py", line 108, in <module>
    main()
  File "app.py", line 53, in main
    userProfile = remote.ReadFromFitbit(fitbitClient.user_profile_get)
  File "/home/jervine/git-checkouts/fitbit-googlefit/remote.py", line 54, in ReadFromFitbit
    resp = api_call(*args,**kwargs)
  File "/usr/lib/python3.5/site-packages/fitbit/api.py", line 256, in user_profile_get
    return self.make_request(url)
  File "/usr/lib/python3.5/site-packages/fitbit/api.py", line 227, in make_request
    response = self.client.make_request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/fitbit/api.py", line 68, in make_request
    response = self._request(method, url, data=data, auth=auth, **kwargs)
  File "/usr/lib/python3.5/site-packages/fitbit/api.py", line 55, in _request
    return self.session.request(method, url, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 299, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 494, in prepare_auth
    r = auth(self)
  File "/usr/lib/python3.5/site-packages/requests_oauthlib/oauth2_auth.py", line 35, in __call__
    http_method=r.method, body=r.body, headers=r.headers)
  File "/usr/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 191, in add_token
    raise ValueError("Missing access token.")
ValueError: Missing access token.

**Comment by jervine** [comment]
PEBKAC ... Had another daemon running on port 8080 locally. Once this was stopped, it magically started working!

**Comment by praveendath92** [comment]
@jervine, Glad you figured it out. Thanks for reporting it back here :smile:
