### ISSUE TITLE
Request Too Large: When pushing data to Google Fit

### ISSUE THREAD

**Issue by rickysarraf** [praveendath92/fitbit-googlefit#3]
When pushing the fitbit data to Google, I got the following (remote) exception.

```
rrs@learner:/var/tmp/lxc/fitbit-googlefit (master)$ python3 app.py 
------------------------------   2016-08-16  -------------------------
synced steps
synced distance
Traceback (most recent call last):
  File "app.py", line 107, in <module>
    main()
  File "app.py", line 85, in main
    remote.SyncFitbitToGoogleFit(fitbitClient,googleClient,'heart_rate',date_stamp,tzinfo)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 112, in SyncFitbitToGoogleFit
    return SyncFitbitIntradayToGoogleFit(fitbitClient, googleClient, dataType, date_stamp, tzinfo)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 149, in SyncFitbitIntradayToGoogleFit
    WriteToGoogleFit(googleClient, dataSourceId, googlePoints)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 73, in WriteToGoogleFit
    point=data_points)
  File "/home/rrs/.local/lib/python3.5/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/rrs/.local/lib/python3.5/site-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 413 when requesting https://www.googleapis.com/fitness/v1/users/me/dataSources/raw%3Acom.google.heart_rate.bpm%3A558973839847%3Afitbit%3Acharge-hr%3Aio.pkp.fbit-gfit/datasets/1471285801000000000-1471372139000000110?alt=json returned "Request Too Large">
2016-08-18 / 15:19:31 ♒♒♒  ☹  => 1  
```

Maybe, because it is an initial sync of my Fitbit data. If so, this exception should be retried.

**Comment by praveendath92** [comment]
This error is on me. Heart rate data is set to seconds precision. So, there's a reading every 10-15 seconds. It never happened with my account but the error is because the app is sending all readings for a single day in one request.

**Comment by praveendath92** [comment]
I will look into splitting the requests. I you don't need such precision for heart rate, I would advice to decrease precision to 1 min.

**Comment by praveendath92** [comment]
You can do that [here](https://github.com/praveendath92/fitbit-googlefit/blob/master/remote.py#L133)

Just change the value to '1min' instead of '1sec'

**Comment by rickysarraf** [comment]
That finally worked. Thank you very much for your immediate response, and also for creating this tool.

```
rrs@learner:/var/tmp/lxc/fitbit-googlefit (master)$ python3 app.py 
------------------------------   2016-08-16  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-17  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

Synced 4 activities : 2016-08-17 -- 2016-08-18

2016-08-18 / 15:34:48 ♒♒♒  ☺  
```

**Comment by praveendath92** [comment]
Glad to see this. Thanks for working through all the issues patiently and reporting them back. Issue #1 is a bit baffling at the moment but I will fix all them soon.

**Comment by praveendath92** [comment]
@rickysarraf , Now you should be able to sync your heart rate with full granularity.
