### ISSUE TITLE
Authentication failing

### ISSUE THREAD

**Issue by ashishnainwal** [praveendath92/fitbit-googlefit#48]
I followed all the steps in github and even youtube video successfully but the authentication is failing. fitbit.json and google.json have also been created successfully. access token in fitbit.json is null.

C:\Desktop\Mydocs\Fitbit-google\fitbit-googlefit-master\fitbit-googlefit-master>python app.py --debug

Traceback (most recent call last):
  File "app.py", line 110, in <module>
    main()
  File "app.py", line 54, in main
    userProfile = remote.ReadFromFitbit(fitbitClient.user_profile_get)
  File "C:\Users\anainwal\Desktop\Mydocs\Fitbit-google\fitbit-googlefit-master\fitbit-googlefit-master\remote.py", line 55, in ReadFromFitbit
    resp = api_call(*args,**kwargs)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\fitbit\api.py", line 256, in user_profile_get
    return self.make_request(url)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\fitbit\api.py", line 227, in make_request
    response = self.client.make_request(*args, **kwargs)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\fitbit\api.py", line 68, in make_request
    response = self._request(method, url, data=data, auth=auth, **kwargs)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\fitbit\api.py", line 55, in _request
    return self.session.request(method, url, **kwargs)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 499, in request
    prep = self.prepare_request(req)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 431, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 307, in prepare
    self.prepare_auth(auth, url)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 538, in prepare_auth
    r = auth(self)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\requests_oauthlib\oauth2_auth.py", line 35, in __call__
    http_method=r.method, body=r.body, headers=r.headers)
  File "C:\Users\anainwal\AppData\Local\Programs\Python\Python36\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 191, in add_token
    raise ValueError("Missing access token.")
ValueError: Missing access token.

**Comment by ashishnainwal** [comment]
fixed...Fitbit has an issue where client secret goes missing ... recreated app to fix it
