### ISSUE TITLE
add some more documentation about sync range.

### ISSUE THREAD

**Issue by rickysarraf** [praveendath92/fitbit-googlefit#5]
The default config.ini marks very recent. To sync all my fitibit data to GFit, I changed it to:

```
[params]

# Starting date of sync (inclusive)
start_date=2016-01-15

# Ending date of sync (exclusive)
end_date=2016-08-18
```

And it mostly works. Just that FitBit is throttling it.

```
rrs@learner:/var/tmp/lxc/fitbit-googlefit (master)$ python3 app.py 
------------------------------   2016-01-16  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-17  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-18  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-19  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-20  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-21  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-22  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-23  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-24  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-25  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-26  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-27  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-28  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-29  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-30  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-01-31  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-01  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-02  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-03  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-04  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-05  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-06  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-07  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-08  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-09  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-10  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-02-11  -------------------------
synced steps
synced distance
synced heart_rate
-------------- Fitbit API rate limit reached ----------
Will retry in 1953 seconds. Time now is : 2016-08-18 15:57:28.011781
synced weight
Traceback (most recent call last):
  File "app.py", line 107, in <module>
    main()
  File "app.py", line 97, in main
    remote.SyncFitbitToGoogleFit(fitbitClient,googleClient,'calories',date_stamp,tzinfo)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 112, in SyncFitbitToGoogleFit
    return SyncFitbitIntradayToGoogleFit(fitbitClient, googleClient, dataType, date_stamp, tzinfo)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 149, in SyncFitbitIntradayToGoogleFit
    WriteToGoogleFit(googleClient, dataSourceId, googlePoints)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 73, in WriteToGoogleFit
    point=data_points)
  File "/home/rrs/.local/lib/python3.5/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/rrs/.local/lib/python3.5/site-packages/googleapiclient/http.py", line 833, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/rrs/.local/lib/python3.5/site-packages/googleapiclient/http.py", line 173, in _retry_request
    raise exception
  File "/home/rrs/.local/lib/python3.5/site-packages/googleapiclient/http.py", line 160, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/rrs/.local/lib/python3.5/site-packages/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)
  File "/home/rrs/.local/lib/python3.5/site-packages/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/rrs/.local/lib/python3.5/site-packages/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/rrs/.local/lib/python3.5/site-packages/httplib2/__init__.py", line 988, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
2016-08-18 / 16:30:03 ♒♒♒  ☹  => 1  
```

I think the exception can be ignored, as it looks mostly like a network error, which could be a temporary one on my laptop.

But, what are those start and end date about ? Does it mean we have to keep upping the end date ?

**Comment by praveendath92** [comment]
The network error is a know issue. It is a bug in one of the libraries. At the moment, it's manually upping the end date but I think it would be nice to have support for something like "today" and the script can parse today's date. 

That way we can setup a cron task which executes ```python3 app.py -s yesterday -e tomorrow``` (2 days everyday)

**Comment by praveendath92** [comment]
http://stackoverflow.com/questions/1495487/is-there-any-python-library-for-parsing-dates-and-times-from-a-natural-language Interesting! Will do this tonight.
